-- WINDOW --
-- window_width,window_height = love.window.getDesktopDimensions()
WINDOW_WIDTH,WINDOW_HEIGHT = 800, 600
WINDOW_WIDTH_CENTER = WINDOW_WIDTH / 2
WINDOW_HEIGHT_CENTER = WINDOW_HEIGHT / 2

-- PLAYER --
PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50
PLAYER_SPEED = 800

-- PROJECTILES --
PROJECTILES_HEIGHT = PLAYER_HEIGHT / 2
PROJECTILES_WIDTH = PROJECTILES_HEIGHT / 2
PROJECTILES_SPEED = 800
PROJECTILES_MAX = 2
PROJECTILES_WAIT = 1

-- ENEMIES --
ENEMY_WIDTH = 50
ENEMY_HEIGHT = 50
ENEMY_SPEED = 400
ENEMIES_COLS = 8
ENEMIES_ROWS = 5
ENEMIES_GAP = 2